version: "3.8"
services:
  app:
    build:
      context: .
    container_name: spring-boot-app
    ports:
      - "${SPRING_APP_PORT}:${SPRING_APP_PORT}" # Spring Boot 포트를 환경 변수로 관리
    depends_on:
      - db
    environment:
      SPRING_APP_PORT: ${SPRING_APP_PORT}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "${MYSQL_PORT}:3306" # MySQL 포트를 환경 변수로 관리
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

